export const 
            PUT = 'PUT', 
            DELETE = 'DELETE', 
            GET = 'GET', 
            POST = 'POST',
            USER_PLACEHOLDER: string = 'https://task.bimit.ru/images/user-placeholder.png',
            FAVORITE_FOOD_IDS: string = 'favorite_food_ids',
            CHOOSE_FOOD: string = 'Выберите еду',
            CHOOSE_ALL: string = 'Выбрать все',
            CANCEL_CHOICE: string = 'Отменить выбор',
            WRONG_ID_FORMAT: string = 'Неверный ID формата еды',
            UPLOAD_PHOTO: string = 'upload_photo',
            BIRTHDATE: string = 'birthdate', 
            BASENAME: string = 'https://task.bimit.ru',
            CONFIRMATION_MESSAGE = 'Вы уверены, что хотите удалить этот элемент?',
            VALUES: Array<string> = ['#', 'ID', 'Фото', 'Имя', 'Email', 'Дата рождения', 'Любимая еда', ''],
            KEYS: Array<string> = ['', 'id', '', 'username', 'email', 'birthdate', 'favorite_food_ids', ''],
            FIELDS: Array<string> = ['ID', 'Имя', 'Email', 'Дата рождения', 'Любимая еда', 'Фото'],
            ARROWS: Array<string> = ['▲', '▼']

